// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "TrailBuddy",
    platforms: [
        .iOS("18.0")
    ],
    products: [
        .iOSApplication(
            name: "TrailBuddy",
            targets: ["AppModule"],
            bundleIdentifier: "pradeep.biswas-mitwpu.edu.in.TrailBuddy",
            teamIdentifier: "J4B79XL3D5",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.orange),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait
            ],
            capabilities: [
                .camera(purposeString: "TrailBuddy uses the camera only when you are lost, to show your AR companion guiding you back."),
                .locationAlwaysAndWhenInUse(purposeString: "TrailBuddy needs background location to keep recording your trail even when your screen is off."),
                .locationWhenInUse(purposeString: "TrailBuddy records your trail offline so your companion can guide you back if you get lost."),
                .motion(purposeString: "TrailBuddy uses your motion sensors to count steps and detect rest breaks during your hike.")
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                .process("Resources")
            ]
        )
    ],
    swiftLanguageVersions: [.version("6")]
)